import { useState, type FormEvent } from "react";
import { ArrowUpRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { SectionHeading } from "./SectionHeading";

export function Contact() {
  const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (event.currentTarget.checkValidity()) setSent(true); else event.currentTarget.reportValidity(); };
  return <section id="contact" className="section-shell bg-background"><div className="mx-auto grid max-w-7xl gap-14 px-5 sm:px-8 lg:grid-cols-2 lg:gap-20 lg:px-12"><div><SectionHeading eyebrow="Find us" title="Come for dinner. Stay for the feeling." /><address className="mt-9 not-italic text-sm leading-7 text-muted-foreground">SAVORA, 10th Floor, Meridian House<br />Koregaon Park, Pune 411001</address><div className="mt-8 grid gap-4 text-sm"><a href="tel:+912067454500" className="contact-link">+91 20 6745 4500 <ArrowUpRight /></a><a href="mailto:hello@savora.in" className="contact-link">hello@savora.in <ArrowUpRight /></a><a href="https://www.google.com/maps/search/?api=1&query=Koregaon+Park+Pune" target="_blank" rel="noreferrer" className="contact-link">Open in Google Maps <ArrowUpRight /></a></div><div className="mt-10 grid grid-cols-2 gap-8 border-t border-border pt-7 text-xs leading-6"><div><p className="section-kicker">Lunch</p><p className="mt-3 text-muted-foreground">Daily<br />12 PM — 3:30 PM</p></div><div><p className="section-kicker">Dinner</p><p className="mt-3 text-muted-foreground">Daily<br />7 PM — 11 PM</p></div></div></div><div className="bg-ink p-7 text-cream sm:p-10">{sent ? <div className="flex min-h-[400px] flex-col items-center justify-center text-center"><Check className="h-10 w-10 text-primary" /><h3 className="mt-5 font-display text-4xl">Thank you.</h3><p className="mt-3 text-sm text-cream-muted">We’ll be in touch shortly.</p><Button variant="goldOutline" size="lg" className="mt-7 border-cream/30 text-cream" onClick={() => setSent(false)}>Send another note</Button></div> : <form onSubmit={submit}><p className="section-kicker">Write to us</p><h3 className="mt-3 font-display text-4xl">How can we help?</h3><div className="mt-8 grid gap-5"><label className="form-label text-cream-muted">Name *<Input required name="name" className="h-12 rounded-none border-cream/20 text-cream" /></label><label className="form-label text-cream-muted">Email *<Input required name="email" type="email" className="h-12 rounded-none border-cream/20 text-cream" /></label><label className="form-label text-cream-muted">Message *<Textarea required name="message" className="min-h-32 rounded-none border-cream/20 text-cream" /></label></div><Button variant="gold" size="lg" type="submit" className="mt-7">Send message</Button></form>}</div></div></section>;
}