import { ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";

const links = [
  ["Home", "home"], ["Our story", "about"], ["Menu", "menu"], ["Experiences", "experience"], ["Gallery", "gallery"], ["Reservations", "reservations"],
] as const;

export function Footer() {
  const goTo = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  return <footer className="bg-ink px-5 pb-8 pt-20 text-cream sm:px-8 lg:px-12"><div className="mx-auto max-w-[1440px]"><div className="grid gap-14 border-b border-cream/15 pb-16 lg:grid-cols-[1.3fr_.7fr_.7fr_1fr]"><div><button type="button" onClick={() => goTo("home")} className="text-left font-display text-5xl">SAVORA</button><p className="mt-5 max-w-xs text-sm leading-7 text-cream-muted">Modern Indian dining shaped by memory, season, and a generous sense of occasion.</p><Button variant="gold" size="lg" className="mt-8" onClick={() => goTo("reservations")}>Reserve a table <ArrowUpRight /></Button></div><div><p className="footer-title">Explore</p><nav className="mt-5 flex flex-col items-start gap-3">{links.slice(0, 4).map(([label, id]) => <button key={id} type="button" onClick={() => goTo(id)} className="footer-link">{label}</button>)}</nav></div><div><p className="footer-title">Visit</p><div className="mt-5 flex flex-col items-start gap-3"><button type="button" onClick={() => goTo("gallery")} className="footer-link">Gallery</button><button type="button" onClick={() => goTo("contact")} className="footer-link">Contact</button><a className="footer-link" href="https://www.instagram.com/" target="_blank" rel="noreferrer">Instagram</a><a className="footer-link" href="https://www.facebook.com/" target="_blank" rel="noreferrer">Facebook</a></div></div><div><p className="footer-title">Contact</p><address className="mt-5 not-italic text-xs leading-6 text-cream-muted">Koregaon Park<br />Pune, Maharashtra<br /><a href="tel:+912067454500" className="transition-colors hover:text-primary">+91 20 6745 4500</a><br /><a href="mailto:hello@savora.in" className="transition-colors hover:text-primary">hello@savora.in</a></address><p className="mt-5 text-xs leading-6 text-cream-muted">Open daily<br />12 PM — 11 PM</p></div></div><div className="flex flex-col gap-3 pt-7 text-[9px] uppercase tracking-[0.2em] text-cream-muted sm:flex-row sm:items-center sm:justify-between"><p>© 2026 SAVORA. All rights reserved.</p><p>Pune · Maharashtra · India</p></div></div></footer>;
}